# Generated by Django 4.0.3 on 2022-05-06 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product_name',
            old_name='product_cat',
            new_name='category_name',
        ),
        migrations.RenameModel(
            old_name='product_cat',
            new_name='Category_name',
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('descreption', models.CharField(max_length=100)),
                ('buy_price', models.IntegerField()),
                ('sell_price', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('category_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Category_get', to='app.category_name')),
            ],
        ),
    ]
