# Generated by Django 4.0.3 on 2022-05-06 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_product_cat_product_name_category_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_name',
            name='category_name',
        ),
        migrations.AlterField(
            model_name='product',
            name='category_name',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Category_name',
        ),
        migrations.DeleteModel(
            name='product_name',
        ),
    ]
